// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlwcohainrraqtuxbdmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsd2NvaGFpbnJyYXF0dXhiZG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTE1MTAsImV4cCI6MjA2OTYyNzUxMH0.Anx0T0hgLVOEgtkoJ5BTpNUEyziI5PK5uMf7qmGAaJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});